site_name: M. Shifat Hossain
site_url: http://shifathossain.github.io
nav:
  - Home: index.md
  - Courses Taken: courses.md
  - Courses Taught: subjects.md
  - Standardized Tests: score.md
  - Publications: publications.md
  - Projects: projects.md
  - Media Coverage: media.md
  - Scientific Papers Reviewed: reviews.md
  - Blogs: blogs/blog_main.md
theme:
  name: material